<log>
  <summary verdicts='2' failures='2' errors='0'/>
  <section name='Test' method='verdict_refute_same?' type='fail'>
    <section name='Args=[:foo, :foo]'>
      <verdict method='verdict_refute_same?' outcome='failed' id='0' message='Message 0'>
        <expected class='Symbol' value=':foo'/>
        <actual class='Symbol' value=':foo'/>
        <exception class='Minitest::Assertion' message='Expected :foo oid=(00000000) to not be the same as :foo oid=(00000000).'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
    <section name='Args=[0, 0]'>
      <verdict method='verdict_refute_same?' outcome='failed' id='1' message='Message 1'>
        <expected class='Integer' value='0'/>
        <actual class='Integer' value='0'/>
        <exception class='Minitest::Assertion' message='Expected 0 oid=(00000000) to not be the same as 0 oid=(00000000).'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
  </section>
</log>
