<log>
  <summary verdicts='3' failures='2' errors='0'/>
  <section name='Test' method='verdict_refute_instance_of?' type='fail'>
    <section name='Args=[Integer, 0]'>
      <verdict method='verdict_refute_instance_of?' outcome='failed' id='0' message='Message 0'>
        <exp_value>
          Integer
        </exp_value>
        <act_value>
          0
        </act_value>
        <exception class='Minitest::Assertion'>
          <message>
            Expected 0 to not be an instance of Integer.
          </message>
          <backtrace/>
        </exception>
      </verdict>
    </section>
    <section name='Args=[Symbol, :a]'>
      <verdict method='verdict_refute_instance_of?' outcome='failed' id='1' message='Message 1'>
        <exp_value>
          Symbol
        </exp_value>
        <act_value>
          :a
        </act_value>
        <exception class='Minitest::Assertion'>
          <message>
            Expected :a to not be an instance of Symbol.
          </message>
          <backtrace/>
        </exception>
      </verdict>
    </section>
  </section>
  <verdict method='verdict_assert_equal?' outcome='passed' id='__error_count__'>
    <exp_value>
      0
    </exp_value>
    <act_value>
      0
    </act_value>
  </verdict>
</log>
