<log>
  <summary verdicts='3' failures='2' errors='0'/>
  <section name='Test' method='verdict_refute_same?' type='fail'>
    <section name='Args=[:foo, :foo]'>
      <verdict method='verdict_refute_same?' outcome='failed' id='0' message='Message 0'>
        <exp_value>
          :foo
        </exp_value>
        <act_value>
          :foo
        </act_value>
        <exception class='Minitest::Assertion'>
          <message>
            Expected :foo oid=(00000000) to not be the same as :foo
            oid=(00000000).
          </message>
          <backtrace/>
        </exception>
      </verdict>
    </section>
    <section name='Args=[0, 0]'>
      <verdict method='verdict_refute_same?' outcome='failed' id='1' message='Message 1'>
        <exp_value>
          0
        </exp_value>
        <act_value>
          0
        </act_value>
        <exception class='Minitest::Assertion'>
          <message>
            Expected 0 oid=(00000000) to not be the same as 0 oid=(00000000).
          </message>
          <backtrace/>
        </exception>
      </verdict>
    </section>
  </section>
  <verdict method='verdict_assert_equal?' outcome='passed' id='__error_count__'>
    <exp_value>
      0
    </exp_value>
    <act_value>
      0
    </act_value>
  </verdict>
</log>
