<log>
  <summary verdicts='3' failures='2' errors='0'/>
  <section name='Test' method='verdict_assert_instance_of?' type='fail'>
    <section name='Args=[Integer, :a]'>
      <verdict method='verdict_assert_instance_of?' outcome='failed' id='0' message='Message 0'>
        <expected class='Class' value='Integer'/>
        <actual class='Symbol' value=':a'/>
        <exception class='Minitest::Assertion' message='Expected :a to be an instance of Integer, not Symbol.'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
    <section name='Args=[Symbol, 0]'>
      <verdict method='verdict_assert_instance_of?' outcome='failed' id='1' message='Message 1'>
        <expected class='Class' value='Symbol'/>
        <actual class='Integer' value='0'/>
        <exception class='Minitest::Assertion' message='Expected 0 to be an instance of Symbol, not Integer.'>
          <backtrace/>
        </exception>
      </verdict>
    </section>
  </section>
  <verdict method='verdict_assert_equal?' outcome='passed' id='__error_count__'>
    <expected class='Integer' value='0'/>
    <actual class='Integer' value='0'/>
  </verdict>
</log>
